configure: Fix check for Solaris audit API to work with gcc 14
Need to declare a variable type to avoid gcc 14 error:

configure:22502: checking for ADT API
conftest.c:107:1: warning: data definition has no type or storage class
  107 | adt_user_context = ADT_USER;
      | ^~~~~~~~~~~~~~~~
conftest.c:107:1: error: type defaults to 'int' in declaration of
 'adt_user_context' [-Wimplicit-int]

Fixes: ab1eb1fd ("Bug 15740: Solaris/ADT auditing support (simon zheng)")
Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>